<template>
    <div>
        <v-img
            width="350"
        ></v-img>
    </div>
</template>

<script>

const srcs = {
    1: '/characters-picture/aatrox.png',
    2: '/characters-picture/ahri.png',
    3: '/characters-picture/akali.png',
    4: '/characters-picture/akshan.png',
    5: '/characters-picture/alistar.png',
    6: '/characters-picture/amumu.png',
    7: '/characters-picture/anivia.png',
    8: '/characters-picture/annie.png',
    9: '/characters-picture/aphelios.png',
    10: '/characters-picture/ashe.png',
    11: '/characters-picture/aurelion_sol.png',
    12: '/characters-picture/aurora.png',
    13: '/characters-picture/azir.png',
    14: '/characters-picture/bard.png',
    15: '/characters-picture/bel\'veth.png',
    16: '/characters-picture/blitzcrank.png',
    17: "/characters-picture/brand.png",
    18: "/characters-picture/braum.png",
    19: "/characters-picture/briar.png",
    20: "/characters-picture/caitlyn.png",
    21: "/characters-picture/camille.png",
    22: "/characters-picture/cassiopeia.png",
    23: "/characters-picture/cho'gath.png",
    24: "/characters-picture/corki.png",
    25: "/characters-picture/darius.png",
    26: "/characters-picture/diana.png",
    27: "/characters-picture/dr._mundo.png",//_?
    28: "/characters-picture/draven.png",
    29: "/characters-picture/ekko.png",
    30: "/characters-picture/elise.png",
    31: "/characters-picture/evelynn.png",
    32: "/characters-picture/ezreal.png",
    33: "/characters-picture/fiddlesticks.png",
    34: "/characters-picture/fiora.png",
    35: "/characters-picture/fizz.png",
    36: "/characters-picture/galio.png",
    37: "/characters-picture/gangplank.png",
    38: "/characters-picture/garen.png",
    39: "/characters-picture/gnar.png",
    40: "/characters-picture/gragas.png",
    41: "/characters-picture/graves.png",
    42: "/characters-picture/gwen.png",
    43: "/characters-picture/hecarim.png",
    44: "/characters-picture/heimerdinger.png",
    45: "/characters-picture/hwei.png",
    46: "/characters-picture/illaoi.png",
    47: "/characters-picture/irelia.png",
    48: "/characters-picture/ivern.png",
    49: "/characters-picture/janna.png",
    50: "/characters-picture/jarvan_iv.png",
    51: "/characters-picture/jax.png",
    52: "/characters-picture/jayce.png",
    53: "/characters-picture/jhin.png",
    54: "/characters-picture/jinx.png",
    55: "/characters-picture/k'sante.png",
    56: "/characters-picture/kai'sa.png",
    57: "/characters-picture/kalista.png",
    58: "/characters-picture/karma.png",
    59: "/characters-picture/karthus.png",
    60: "/characters-picture/kassadin.png",
    61: "/characters-picture/katarina.png",
    62: "/characters-picture/kayle.png",
    63: "/characters-picture/kayn.png",
    64: "/characters-picture/kennen.png",
    65: "/characters-picture/kha'zix.png", 
    66: "/characters-picture/kindred.png",
    67: "/characters-picture/kled.png",
    68: "/characters-picture/kog'maw.png",
    69: "/characters-picture/leblanc.png",
    70: "/characters-picture/lee_sin.png",
    71: "/characters-picture/leona.png",
    72: "/characters-picture/lillia.png",
    73: "/characters-picture/lissandra.png",
    74: "/characters-picture/lucian.png",
    75: "/characters-picture/lulu.png",
    76: "/characters-picture/lux.png",
    77: "/characters-picture/malphite.png",
    78: "/characters-picture/malzahar.png",
    79: "/characters-picture/maokai.png",
    80: "/characters-picture/master_yi.png",
    81: "/characters-picture/milio.png",
    82: "/characters-picture/miss_fortune.png",
    83: "/characters-picture/mordekaiser.png",
    84: "/characters-picture/morgana.png",
    85: "/characters-picture/naafiri.png",
    86: "/characters-picture/nami.png",
    87: "/characters-picture/nasus.png",
    88: "/characters-picture/nautilus.png",
    89: "/characters-picture/neeko.png",
    90: "/characters-picture/nidalee.png",
    91: "/characters-picture/nilah.png",
    92: "/characters-picture/nocturne.png",
    93: "/characters-picture/nunu_&_willump.png",
    94: "/characters-picture/olaf.png",
    95: "/characters-picture/orianna.png",
    96: "/characters-picture/ornn.png",
    97: "/characters-picture/pantheon.png",
    98: "/characters-picture/poppy.png",
    99: "/characters-picture/pyke.png",
    100: "/characters-picture/qiyana.png",
    101: "/characters-picture/quinn.png",
    102: "/characters-picture/rakan.png",
    103: "/characters-picture/rammus.png",
    104: "/characters-picture/rek'sai.png",
    105: "/characters-picture/rell.png",
    106: "/characters-picture/renata_glasc.png",
    107: "/characters-picture/renekton.png",
    108: "/characters-picture/rengar.png",
    109: "/characters-picture/riven.png",
    110: "/characters-picture/rumble.png",
    111: "/characters-picture/ryze.png",
    112: "/characters-picture/samira.png",
    113: "/characters-picture/sejuani.png",
    114: "/characters-picture/senna.png",
    115: "/characters-picture/seraphine.png",
    116: "/characters-picture/sett.png",
    117: "/characters-picture/shaco.png",
    118: "/characters-picture/shen.png",
    119: "/characters-picture/shyvana.png",
    120: "/characters-picture/singed.png",
    121: "/characters-picture/sion.png",
    122: "/characters-picture/sivir.png",
    123: "/characters-picture/skarner.png",
    124: "/characters-picture/smolder.png",
    125: "/characters-picture/sona.png",
    126: "/characters-picture/soraka.png",
    127: "/characters-picture/swain.png",
    128: "/characters-picture/sylas.png",
    129: "/characters-picture/syndra.png",
    130: "/characters-picture/tahm_kench.png",
    131: "/characters-picture/taliyah.png",
    132: "/characters-picture/talon.png",
    133: "/characters-picture/taric.png",
    134: "/characters-picture/teemo.png",
    135: "/characters-picture/thresh.png",
    136: "/characters-picture/tristana.png",
    137: "/characters-picture/trundle.png",
    138: "/characters-picture/tryndamere.png",
    139: "/characters-picture/twisted_fate.png",
    140: "/characters-picture/twitch.png",
    141: "/characters-picture/udyr.png",
    142: "/characters-picture/urgot.png",
    143: "/characters-picture/varus.png",
    144: "/characters-picture/vayne.png",
    145: "/characters-picture/veigar.png",
    146: "/characters-picture/vel'koz.png",
    147: "/characters-picture/vex.png",
    148: "/characters-picture/vi.png",
    149: "/characters-picture/viego.png",
    150: "/characters-picture/viktor.png",
    151: "/characters-picture/vladimir.png",
    152: "/characters-picture/volibear.png",
    153: "/characters-picture/warwick.png",
    154: "/characters-picture/wukong.png",
    155: "/characters-picture/xayah.png",
    156: "/characters-picture/xerath.png",
    157: "/characters-picture/xin_zhao.png",
    158: "/characters-picture/yasuo.png",
    159: "/characters-picture/yone.png",
    160: "/characters-picture/yorick.png",
    161: "/characters-picture/yuumi.png",
    162: "/characters-picture/zac.png",
    163: "/characters-picture/zed.png",
    164: "/characters-picture/zeri.png",
    165: "/characters-picture/ziggs.png",
    166: "/characters-picture/zilean.png",
    167: "/characters-picture/zoe.png",
    168: "/characters-picture/zyra.png",
  }



</script>

<style>

</style>